### ISSUE TITLE
Load images from a configurable path

### ISSUE THREAD

**Issue by jackpot51** [robbycerantola/pastel#2]
Loving pastel so far. It is now being packaged for Redox.

The only issue is that the icons need to be loaded from an absolute path. It would be good if the base path could be passed in the compiler environment using `env!`, such as `ASSET_PATH`

**Comment by robbycerantola** [comment]
I've made some little changes so the working path will be set at compile time based on the target os .
Now it works both in linux and redox.

**Comment by jackpot51** [comment]
Cool!
