### ISSUE TITLE
Continuus brush

### ISSUE THREAD

**Issue by BojanKogoj** [robbycerantola/pastel#7]
On the image below (top line) you can see if I draw quickly with a brush the line is made of circles. Is it possible to make it like the bottom line, that I made by drawing slowly?

![image](https://user-images.githubusercontent.com/634075/32414008-827f71f0-c21d-11e7-86f0-c210b7559c43.png)

**Comment by robbycerantola** [comment]
@BojanKogoj  I think that the last commit fixes your issue. Now, to get some transparency you have to set opacity very low , (under 20 % or so).

**Comment by BojanKogoj** [comment]
Works great, thanks!
